#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

  if [ -z "${2-}" ]; then
    # By default git hooks are not interactive. exec < /dev/tty allows a users terminal to interact with commitizen.
    exec < /dev/tty && npx cz --hook || true
  fi

