name: Accessibility Test

on:
  push:
    branches: [v3]
  pull_request:
    branches: [v3]

permissions:
  contents: read

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Oobee
        run: pnpm run test:a11y:setup

      - name: Run accessibility tests
        run: pnpm run test:a11y

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: a11y-results
          path: |
            a11y-results.zip
            results/
          if-no-files-found: ignore
