name: Publish Pre-releases

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'


jobs:
  publish:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag env
        run: echo "NPM_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: |
          gem install bundler
          bundle install
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build:lib
      - run: npm publish --tag alpha --access public
        if: contains(env.NPM_TAG, 'alpha')
      - run: npm publish --tag beta --access public
        if: contains(env.NPM_TAG, 'beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}