name: Publish Pre-releases

on:
  push:
    tags:
      - 'sgds/v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'sgds/v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'sgds-x-family/v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'sgds-x-family/v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:
  publish-sgds:
    if: startsWith(github.ref, 'refs/tags/sgds/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm run lib:install   
      - run: npm run lib:build
      - run: cd lib/sgds && npm publish --tag alpha --access public 
        if: contains(env.NPM_TAG, 'alpha')
      - run: cd lib/sgds && npm publish --tag beta --access public
        if: contains(env.NPM_TAG, 'beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-sgds-x-family:
    if: startsWith(github.ref, 'refs/tags/sgds-x-family/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run sgds-x-family:build
      - run: cd lib/sgds-x-family
      - run: npm publish --tag alpha --access public
        if: contains(env.NPM_TAG, 'alpha')
      - run: npm publish --tag beta --access public
        if: contains(env.NPM_TAG, 'beta')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
