name: Publish

on:
  push:
    branches:
      - ghAction-publish-master

jobs:
  publish:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - run: |
          gem install bundler
          bundle install
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build:lib
      # - name: Version Check
      #   uses: EndBug/version-check@v2.1.0
      #   id: check
      - run: npm publish --tag latest --access public
        # if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}